---
title: "MUSA 5080 Portfolio"
---

# Welcome to My Portfolio

This portfolio documents my learning journey in Public Policy Analytics (MUSA 5080).

## About This Course
Advanced spatial analysis and data science for urban planning and public policy.

## Portfolio Structure
- **Weekly Notes:** My learning reflections and key concepts
- **Labs:** Completed assignments and analyses
- **Exercise:** Completed assignments and analyses
- **Final Project:** Capstone modeling challenge

## About Me
**Hello!** I am Matthew Levy — a Master's of [City Planning](https://www.design.upenn.edu/city-regional-planning/graduate/graduate-city-and-regional-planning-programs) and [Urban Spatial Analytics](https://www.design.upenn.edu/urban-spatial-analytics/master-urban-spatial-analytics) student at the University of Pennsylvania. I grew up in Bexley, OH (an inner suburb of Columbus, Go Bucks!) and completed my undergrad at Indiana University, where I studied [Informatics](https://informatics.indiana.edu/) with a concentration in Geography.

Outside of school, I love to read (my favorite book is *James*!), bike, and eat. I am also a massive Packers fan, so I will always be down to sing the praises of the Green and Gold.

## Contact
- Email: mblevy@upenn.edu
- GitHub: MBLevy
